FROM golang:1.23-alpine

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /app
COPY db/migrations /migrations

CMD ["sh", "-c", "sleep 5 && goose -dir /migrations postgres 'postgres://chat:chat@chat-postgres:5432/chat?sslmode=disable' up"]